### PR TITLE
Refactor AppController+Sparkle from Objective-C to Swift.

### PR DESCRIPTION
**Pull request by nielspl**
Refactor obj-c code to Swift.

### CODE REVIEW

**Comment by barijaona** [comment]
@Eitot , you mentioned that you intend to bring soon further changes to preferences. Do you foresee possible interferences ?

**Comment by Eitot** [comment]
> @Eitot , you mentioned that you intend to bring soon further changes to preferences. Do you foresee possible interferences ?

No, no problems there. This I can simply merge.

**Review by barijaona — DISMISSED** [review]

**Review by Eitot — APPROVED** [review]
Rebased onto master.

**Comment by Eitot** [comment]
@nielspl Thanks!

**Pull request merged**
