### PR TITLE
Code cleanup

### PR DESCRIPTION
**Pull request by josh64x2**
Removed more` #DEFINE`s from the code to modernise the code and make it more Swift compatible.

Details in the commits.

### CODE REVIEW

**Comment by barijaona** [comment]
What impact on performance will have the proposed change to StringExtensions ?

**Comment by barijaona** [comment]
The change to StringExtensions is probably unneeded : https://stackoverflow.com/questions/37934161/how-does-this-define-work-in-swift

**Comment by josh64x2** [comment]
What performance concerns do you have specifically? I did not notice any...

#define are an ugly hack and should be avoided anyway.

**Comment by josh64x2** [comment]
There was no noticeable performance impact - Instruments.app didnt show anything had slowed down.

**Comment by barijaona** [comment]
Josh wrote :
> #define are an ugly hack and should be avoided anyway.
> 

Do you think so ? C- preprocessor and #define-s are the best thing since the invention of hot potatoes 😉😊🤣

Seriously, you can leave the implementation as it is, as it is a perfect fit for Objective-C while Swift does not need SafeString at all

**Pull request merged**
