### PR TITLE
Fixed unwanted column resizing in vertical layout

### PR DESCRIPTION
**Pull request by barijaona**
Problem seen with macOS 11 : when article has an enclosure file, the
width of article view resizes abruptly to accomodate the enclosure bar
at the bottom of the article pane to length of the enclosure filename.

Fixed by modifying some constraints priority
Issue #1370

### CODE REVIEW

**Review by Eitot — CHANGES_REQUESTED** [review]
It does not fix the issue, sadly. I was able to reproduce it again with your changes by jumping between feed items with and without attachments and across feeds.

**Comment by Eitot** [comment]
Can you try my changes?

**Comment by barijaona** [comment]
Thanks for the hint. But I'd prefer more flexibility in width of article view : your changes does not allow the filename to be compressed.

**Comment by barijaona** [comment]
@Eitot, I took your approach but slightly modified it. Can you have another look ?

**Comment by Eitot** [comment]
@barijaona: There is still a problem. I think you can reproduce it like this:
1. Go to a feed that does not have an attachment.
2. Switch to a feed with an attachment.
3. Resize the article view horizontally (even just a little is enough)
4. Switch to a feed that does not have an attachment.
5. Switch to a feed with an attachment. The article view should not constrict to the label width.

**Comment by Eitot** [comment]
@barijaona: I made a small fix to my PR and uploaded it to this branch: https://github.com/Eitot/Vienna/tree/pr-1751. This stops the file name from narrowing the article view. I have not been able to reproduce the ‘jumping’ issue with this.

**Comment by barijaona** [comment]
I am OK with your last changes. Same behavior than Vienna 3.5.10

**Review by Eitot — APPROVED** [review]
Seems to be fixed now.

**Pull request merged**
