### PR TITLE
Resolve some Objective-C warnings in Xcode 9

### PR DESCRIPTION
**Pull request by Eitot**
Xcode 9 warned me about these, but they should work regardless.

### CODE REVIEW

**Comment by barijaona** [comment]
It crashes on me (with macOS 10.12.5, Xcode 8.3.3)… I don't have time to investigate immediately, but will be back at it as soon as possible.

**Comment by Eitot** [comment]
Cannot confirm this myself; I need more information.

**Comment by Eitot** [comment]
Should be resolved now.

**Comment by barijaona** [comment]
Yes, the modified version runs fine.

Just an aside remark : you modified some indents in `StringExtensions.m`. It is currently [recommended](https://github.com/ViennaRSS/vienna-rss/blob/master/CONTRIBUTING.md) to use 4 spaces, [not tabs](https://github.com/spotify/ios-style).
Personally, I use the uncrustify script with [this config](https://gist.github.com/barijaona/949a685db2e097fdb031acc24f1c4035) to beautify new or heavily refactored c

**Comment by Eitot** [comment]
The changes here are tabs to spaces. Xcode 9 seems to be a bit more aggressive in correcting this. I spoke to Josh earlier and it is perhaps advisable to do a mass-PR and correct all tabs project-wide to enforce the guidelines. Just to avoid having large incidental commits.

**Pull request merged**
