### PR TITLE
Database refactor

### PR DESCRIPTION
**Pull request by josh64x2**
Hi @barijaona , this change is now ready for discussion and testing.
The basics work (e.g. marking articles as read, refreshing subscriptions).
I still need to test at least the following but I plan on writing some unit tests over the next few days for them:
1. Creating a database when none exists
2. Upgrading a database schema from a previous version
3. Importing subscriptions from OPML
4. Creating / deleting folders
5. Smart folders
6. ???
7. Profit!!!

Included in this changeset are some changes to the project scheme. As a result the Makefile and travis config have also changed. I need to discuss these changes with you as well.

### CODE REVIEW

**Comment by josh64x2** [comment]
I realise the commit history is ugly - and contains duplicates :frowning: Please tell me if you know how to fix this.

**Comment by barijaona** [comment]
A lot of good things here ! Database.m/h are much more legible with these changes. I confess I had a love/hate relationship with the low level approach of original versions, but let's recognize we are in the 21st century ! ;-)

1. To remove duplicates from the commit history, I would suggest you create a new branch (based on the current master) and perform iterative cherrypicking. You may also directly checkout some final files in order to amend commits and make the history shorter and easier to read.
2. The database scheme migration is currently broken (you can check this by downloading [Vienna 2.0.1](https://sourceforge.net/projects/vienna-rss/files/ReleasedVersions/2.0.1.2028/), initializing a new database with it, and launching the latest version)
3. We probably need to update a few things in the Word document DatabaseSchema.doc . At least, we need to replace reference to `[Database sharedDatabase]`with `[Database sharedManager]`

**Comment by josh64x2** [comment]
OK thanks for the feedback! I've also discovered there are some issues with recursive calls to the FMDatabaseQueue being made which is probably a design problem - I'll be looking in to that and also testing the migration later today.

**Comment by barijaona** [comment]
Yeah, the unread articles count/status on Open Reader feeds seem to behave strangely.

**Comment by josh64x2** [comment]
Replaced by PR #436

**Pull request closed without merging**
