### PR TITLE
Add GitHub workflow for testing Vienna

### PR DESCRIPTION
**Pull request by josh64x2**
Eventually we can replace Travis with GitHub workflows.

### CODE REVIEW

**Comment by josh64x2** [comment]
I think the Test step is failing because the tests are hosted and the App launches - this isn't working in headless mode properly.

**Comment by Eitot** [comment]
Github Actions is leaving beta on 13 November. For public repos it looks to be free.

**Comment by Eitot** [comment]
> I think the Test step is failing because the tests are hosted and the App launches - this isn't working in headless mode properly.

Vienna probably ought to be configured for headless testing.

**Comment by josh64x2** [comment]
Replaced by #1289

**Pull request closed without merging**
