### PR TITLE
Update FMDB to 2.7.2

### PR DESCRIPTION
**Pull request by Eitot**
Needs testing.

### CODE REVIEW

**Comment by Eitot** [comment]
Travis' Pods cache appears to be outdated. Will re-test later.

**Comment by josh64x2** [comment]
Summary of changes here: https://github.com/ccgus/fmdb/blob/master/README.markdown#whats-new-in-fmdb-27

**Comment by josh64x2** [comment]
I noticed this in the travis build log:
```
⚠️  /Users/travis/build/ViennaRSS/vienna-rss/src/VNADatabaseMigration.m:57:47: 'objectForColumnName:' is deprecated: Use objectForColumn instead [-Wdeprecated-declarations]
                NSNumber *folderId = [results objectForColumnName:@"folder_id"];
                                              ^
⚠️  /Users/travis/build/ViennaRSS/vienna-rss/src/VNADatabaseMigration.m:58:47: 'objectForColumnName:' is deprecated: Use objectForColumn instead [-Wdeprecated-declarations]
                NSNumber *parentId = [results objectForColumnName:@"parent_id"];
```

**Comment by Eitot** [comment]
Just a name change:
> To become consistent with the rest of the API, the methods objectForColumnName and UTF8StringForColumnName have been renamed to objectForColumn and UTF8StringForColumn.

I will push a fix.

**Pull request merged**
