### PR TITLE
Remove some unused code from AppController

### PR DESCRIPTION
**Pull request by Eitot**
- Moves the Dock menu to Interface Builder
- Restores the default background of the sidebar
- Removes unused outlets

I will be pushing some more commits to it, but it would be good if you could test these commits already.

### CODE REVIEW

**Comment by josh64x2** [comment]
This is looking great! I like the translucent sidebar.

**Comment by Eitot** [comment]
Sidebar needs more work unfortunately, I have tried to keep the changes minimal in this PR.

**Comment by josh64x2** [comment]
Is this OK to start reviewing? I would like to have it merged into `master` so I can take some screenshots of Vienna for the new website.

**Comment by Eitot** [comment]
All right, I have no time currently to add more stuff.

**Pull request merged**
