### PR TITLE
Modernize Code (10.9 or later)

### PR DESCRIPTION
**Pull request by barijaona**
- convert remaining NIBs to XIBs 
- convert to Base internationalization and create localized .strings
- simplify InfoWindow by removing DisclosableView
- convert XIBs to AutoLayout (with the help of a new DisclosureView class)
- other small changes

### CODE REVIEW

**Comment by barijaona** [comment]
@josh64x2 , in case you have some time, I'm just curious.
Can you confirm that despite use of the modified DisclosureView class, this branch does not work under 10.8 ?

**Comment by josh64x2** [comment]
@barijaona sure I'll check later today.

**Comment by josh64x2** [comment]
OK it still has the constraint issues that we were getting previously, as well as some new issues relating to loading plugins.
I've put the log here https://gist.github.com/64576c5ec88529849b8a6bc3b30c184c

**Comment by josh64x2** [comment]
Works fine on 10.12 btw

**Pull request merged**
