### PR TITLE
New Crowdin translations

### PR DESCRIPTION
**Pull request by Eitot**
Enjoy!

### CODE REVIEW

**Comment by Eitot** [comment]
Like Whac-A-Mole…

I’ll wait until the end of the week before I merge this.

**Comment by josh64x2** [comment]
I was contacted by Andrius through crowdin who wants to contribute a Lithuanian translation.

**Comment by RobFog** [comment]
What about the "do not merge" label?

**Comment by Eitot** [comment]
I was actually waiting for the merger of #1087. I will submit a new PR for this.

**Pull request merged**
