### PR TITLE
Rewrite tests to Swift

### PR DESCRIPTION
**Pull request by nielspl**
Rewrite tests to Swift, except 2 tests in ArticleTests.m that check for NSException (not available in Swift).

### CODE REVIEW

**Review by Eitot — CHANGES_REQUESTED** [review]
Could you reformat the Swift files to use spaces instead of tabs?

**Comment by Eitot** [comment]
Looks good to me. Thanks for this.

This probably cannot be merged just yet since it touches files that the WebKit PR changes too.

**Comment by barijaona** [comment]
In changes like these, risk may outweigh gains…
Possible risk : subtle unpredicted behavioral change
Possible gain : slightly more legible for newcomers

**Comment by TAKeanice** [comment]
I think Swift tests are generally more safe as they implicitly test nullability, i.e. Objective-C / Swift interoperability. However, we should maybe additionally keep the other implementation for excluding the possibility of regressions.

**Comment by nielspl** [comment]
I will fix the tabs/spaces in the swift files and keep the original obj-c code.

**Comment by barijaona** [comment]
> I will fix the tabs/spaces in the swift files and keep the original obj-c code.

@nielspl I sent you a pull request regarding tabs/spaces a few days ago.

**Comment by TAKeanice** [comment]
Hi @nielspl , I rebased the test rewrites onto the current master. @barijaona s indentation corrections are already included. If you want to compare to your original commits, I pushed https://github.com/TAKeanice/vienna-rss/tree/TestsToSwift_backup to my repository. The article tests are already included in the now merged webkit browser branch.

**Comment by TAKeanice** [comment]
@barijaona @nielspl @Eitot shouldn´t we merge this?

**Review by TAKeanice — APPROVED** [review]

**Pull request merged**
