### PR TITLE
Clean up some code relating to ViennaApp/AppController

### PR DESCRIPTION
**Pull request by Eitot**
Replaces `-handleAbout` and `-exitVienna` with standard NSApplication methods.

### CODE REVIEW

**Comment by barijaona** [comment]
I have some reservation with 512f91b

At a time, many websites were sniffing the type and version of the web browsers and simply refused to deliver content to unknown browsers.
So we had no other recourse than pretending being the latest Safari.
See for instance commit 198826f6859a052703e9a65bcb05a390bcbe5d8d and the [user complaint](http://m.yhub.us/image/3z0H3o2a3W3X) it refers to.

**Comment by Eitot** [comment]
Yuck, that is very unfortunate. 😔 Do you happen to know whether the current implementation is sandbox-proof?

**Comment by barijaona** [comment]
I cannot verify regarding this particular situation, but I am pretty sure a lot of sites (on internet or private intranets) still use browser sniffing even if it is widely recommended against.

**Comment by Eitot** [comment]
It does seem to be sandbox-proof at least. We may have to revisit this once we switch to WKWebView.

I’ll drop this for now.

**Comment by Eitot** [comment]
I spotted a bug in this

**Comment by barijaona** [comment]
I agree that the "About" command in status menu has no real use.
 
But it is not so unusual to have items in status menu which duplicate the Dock… Many people have the Dock hidden in System Preferences (hey, some of us used Macs before MacOS X appeared :smile:). Therefore, using the status menu to bring Vienna to become the frontmost app is quite convenient.

Request #292 illustrates that some people extensively use status menu and don't use the Dock at all…

For the record : open and quit items were added in commits 7d23df2 and bba2ac3

**Pull request merged**
