### PR TITLE
Update project

### PR DESCRIPTION
**Pull request by barijaona**
- Fix error raised by SwiftLint (issue #1108)
- Recommended project updates by Xcode 9.3

Note that many warnings remain, but they can be worked on later.

### CODE REVIEW

**Comment by TAKeanice** [comment]
What about upgrading cocoapods to the current version when we are already updating the xcode project?

**Comment by TAKeanice** [comment]
This PR conflicts with https://github.com/ViennaRSS/vienna-rss/pull/1110 due to XCode project changes. Possibly the first commit only would work.

**Comment by barijaona** [comment]
What do you mean by conflict ?
From my experience, if you run Xcode 9.3, this one should be applied before #1110, but they do not conflict per se.

**Comment by TAKeanice** [comment]
And it is a hell lot of changes in the project.pbxproj file, so I would suggest you rebase this PR onto #1110 or onto the current master after it has been merged, or you re-do the changes then.

**Comment by barijaona** [comment]
Which version of Xcode do you use ?

**Comment by TAKeanice** [comment]
Version 9.3, on the latest OSX (High Sierra, 10.13.4). So in the tab_bar_refactoring project changes, the update should already be included. I do not have swift-lint installed though, so I cannot get the error you encounter in #1108. For me, it just issues a warning that it is not installed.
The problem is, that in tab_bar_refactoring, the changes to the project file include the addition of MMTabBar and the deletion of PSMTabBar, and to disentangle these changes cleanly when resolving the merge conflicts is enormously tedious.

**Comment by TAKeanice** [comment]
It is, however, seamlessly possible to cherry-pick only https://github.com/ViennaRSS/vienna-rss/pull/1109/commits/22426cf702d265e995f9d6d3c59023c2e679c14c . I would recommend to do the recommended project changes from https://github.com/ViennaRSS/vienna-rss/pull/1109/commits/8a2f3c671e027f9385690d40dfd33097fb25c0c0 in another PR

**Comment by barijaona** [comment]
This is weird, because neither my Xcode nor Travis CI complain about a conflict…

But anyway, let's do it the way you suggest. I'll close this and you can submit a new PR cherry-picking  22426cf.

**Pull request closed without merging**
