### PR TITLE
Webkit browser

### PR DESCRIPTION
**Pull request by barijaona**
rebased #1312 on current master

### CODE REVIEW

**Comment by barijaona** [comment]
@TAKeanice: the article tests currently need a fix. During the discussion [around #1348](https://github.com/ViennaRSS/vienna-rss/pull/1348#discussion_r519207167), you wrote that you intended to refactor these tests. It's probably time to convert them into Swift as well (cf. #1387).

I can do it as an exercice for myself, but I would need some clues about your intentions…

**Comment by TAKeanice** [comment]
There is an ArticleConverter class with two subclasses, one for WebView and one for WebKit. Those have the functionality to be tested

**Comment by TAKeanice** [comment]
Nice one @Eitot , I wasn't aware that the "==" check works for self-defined `NSUserInterfaceItemIdentifier`s with identifiers defined elsewhere.

**Review by Eitot — APPROVED** [review]
@ViennaRSS/maintainers: Please also add your review.

I think the implementation is stable. The new browser is presently opt-in. Further changes can be made in separate commits.

**Comment by TAKeanice** [comment]
After merging we should think about how we present the option to activate the new browser and encourage users to test and submit feedback for it!

**Review by josh64x2 — APPROVED** [review]

**Review by TAKeanice — APPROVED** [review]

**Comment by TAKeanice** [comment]
🎉

**Pull request merged**
