### PR TITLE
Remove unused ViewExtensions files

### PR DESCRIPTION
**Pull request by Eitot**
The only references were in AppController and they were removed as a result of 9dacb6d and 3f0b185 (DisclosureView).

### CODE REVIEW

**Comment by josh64x2** [comment]
I'll try and merge all of these in order tonight.

This blog post has an interesting approach we could consider for AppController https://medium.com/ios-os-x-development/pluggableapplicationdelegate-e50b2c5d97dd#.3dh3nkpdt

**Comment by Eitot** [comment]
That is a good approach, yes. I was already looking at grouping related code into category extensions a few days ago. We just have to be carful that we are not just sidestepping the problem of simply having too much code in the delegate to begin with. At the least, all the main menu and main window  code has to be somewhere lese.

**Comment by josh64x2** [comment]
Agreed! Can you please look at my outstanding PRs and approve them if you think they are OK?

**Comment by Eitot** [comment]
I can only confidently approve the 10.9 changes. The database is a bit over my head, though it seems to work just fine.

**Pull request merged**
