### PR TITLE
Prepare project for Swift

### PR DESCRIPTION
**Pull request by Eitot**
Adds a bridging header and makes some changes to the project configuration (all done by Xcode). Merge #812 first.

### CODE REVIEW

**Comment by barijaona** [comment]
@Eitot, could you rebase on current master to solve conflicts ?

**Comment by barijaona** [comment]
Aside note : as incorporation of Swift runtime library will significantly increase the size of future builds, and binary compatibility will not stabilize soon, we should consider enabling Sparkle’s [delta updates](https://sparkle-project.org/documentation/delta-updates/).

**Comment by josh64x2** [comment]
oh that didnt work out too well - I tried to resolve the conflict through the webui... oops.

**Comment by Eitot** [comment]
No worries, done.

**Comment by Eitot** [comment]
Will one of you make a separate PR for the Sparkle delta updates? Josh mentioned elsewhere that we aren’t using `generate_appcast` yet, which apparently takes care of deltas automatically. Instructions are at the page linked above and at https://sparkle-project.org/documentation.

**Pull request merged**
