### PR TITLE
Convert macros in Folder class

### PR DESCRIPTION
**Pull request by josh64x2**
This will enhance future Swift compatibility.
- Converted folder types to NS_ENUM type VNAFolderType - VNA Namespace required due to conflicting OSType of FolderType
- Find and replaced folder types to the NS_ENUM name
- Changed Folder.type to a real property and updated the type of it to VNAFolderType
- more coming soon

### CODE REVIEW

**Comment by josh64x2** [comment]
@Eitot as discussed earlier...

**Comment by josh64x2** [comment]
My next PR will replace the Folder flags with `NS_OPTIONS` enums.

**Comment by barijaona** [comment]
Hey Josh, please give us a little more time for reviews… You can continue working in your private branches, but be careful with master…

**Comment by josh64x2** [comment]
@barijaona it had already been reviewed and approved by @Eitot

**Comment by barijaona** [comment]
Oh, sorry, didn't see it…

**Comment by josh64x2** [comment]
no worries :)

**Comment by barijaona** [comment]
The cause is that the RSS feed provided by Github does not mention reviews :smile:

**Pull request merged**
