### PR TITLE
Configure app to close abandoned issues

### PR DESCRIPTION
**Pull request by barijaona**
https://github.com/apps/stale

### CODE REVIEW

**Review by josh64x2 — APPROVED** [review]

**Review by josh64x2 — CHANGES_REQUESTED** [review]
Actually we need to see why the CI build is failing first.

**Comment by TAKeanice** [comment]
Mine always fail due to this: https://github.com/ViennaRSS/vienna-rss/issues/1321

**Comment by josh64x2** [comment]
oh yeah i remember now. I'll take a look at fixing it tonight or tomorrow morning and create a PR.

**Comment by josh64x2** [comment]
Ok this is ready after #1328 is merged.

**Pull request merged**
