### PR TITLE
Fixed loading of tabs, implemented delayed loading on re-open (#1061), and tab visit order (#1070)

### PR DESCRIPTION
**Pull request by TAKeanice**
The bug of forgetting tab urls described in #1061 was due to delayed loading on opening the tab, which caused the URL of the tab not set when quitting the application.
The other problem was solved by only re-loading tabs when they are selected. This makes the whole startup much faster than before. Tabs still load when being opened for the first time from the feed, though. In that respect the old behavior did not change. This helps with displaying the correct title for the tab soon after opening it, and accounts for that users probably want to read the tab content during the session.

### CODE REVIEW

**Comment by TAKeanice** [comment]
Sorry about the titles, I didn’t find a solution for reliably loading just the title of a site without its content. Before my change, tab titles were „loading“ until the tab had reloaded. I could try a website „HEAD“ request to solve that. But also now it’s only the first time after the update. The implementation of the model for the tabs is somewhat implicit so there is no real data structure that could support an ordering. But I can probably do a larger restructuring of the tabbing next week to solve #1070.

**Comment by josh64x2** [comment]
Firstly, this looks great - your code is very clean and I'm really happy to have a PR of this quality so thank you!

However, each time a new tab opens I am seeing the following message in the Xcode console:
```
2018-02-12 15:00:00.513450+0800 Vienna[6623:108837] *** Assertion failure in -[PSMTabBarCell _objectValue:forString:errorDescription:], /BuildRoot/Library/Caches/com.apple.xbs/Sources/AppKit/AppKit-1561.40.104/AppKit.subproj/NSCell.m:1692
```

Could you please look into this?

Thanks again :)

**Comment by TAKeanice** [comment]
Ok the last changes fix some of the oddness of titles and add the feature #1070 (although not in a persistent manner). I have added two booleans into the interface in `BrowserPane.m` that should be present in the preferences, to make the tabbing behaviour configurable according to the reading preferences of the user. If @josh64x2 or @barijaona could change the preferences it would be nice!

**Comment by TAKeanice** [comment]
I could not reproduce your observation though, @josh64x2 . Maybe because I freshly installed the pods when I first downloaded the project. The assertion failure you see seems to originate from the PSMTabBar, which could be a newer version in my project due to the fresh installation.

**Comment by barijaona** [comment]
Not sure I understand the latest commits : why is the primary tab treated differently ?
I guess that most of the time, the user expects to return to the article list after having read the details of an article.

**Comment by TAKeanice** [comment]
The first commit are just fixes to the tab title saving (there were a couple of bugs in my first commit).

The second commit is about the order that tabs are opened when the current one gets closed:

As suggested in #1070 , I implemented, that the last visited tab gets opened once the current one gets closed. This has the benefit that not a random tab that happens to be left or right of the current one gets opened and loaded, which is beneficial to the lazy tab loading I implemented as a solution for #1060 . The first tab is treated differently because I assumed that if a user opened multiple tabs, he changes to the tabs from the reading list to read them. It would be really annoying to return to the article list every time when closing a tab.

The user setting is for users who actually want the old Safari-like behavior: Just opening the tab right of the current one when the current one is closed, and if the current tab was the last one opening the tab that is left of the current one. We could make it default to have the old behavior by disabeling the tab-order option.

The user setting has a second part: When a tab is opened, does it move to the last or the first spot in the order? This setting can be omitted and we can just use a sensible default. It depends on a user´s habits though, if he reads the tabs he has opened from left to right (`selectNewItemFirst = NO`) or from right to left ('selectNewItemFirst = YES'). The setting only applies if the tab ordering option is enabled.

**Comment by TAKeanice** [comment]
We could implement actually #1071 in order to move to the article tab faster, which would mitigate the special treatment when closing tabs.

**Comment by josh64x2** [comment]
OK this is looking good - I  haven't been able to reproduce the assertion failure I was getting previously so let's just blame it on macOS 10.13 being a bit weird :)

I hope to have some time to work on the preferences this weekend.

Could you please put your commits in a new branch on your fork of the repository so they aren't directly on `master`?

Thanks 😄

**Comment by TAKeanice** [comment]
I changed the branch in my fork and recreated the pull request (new request: #1088 )

**Pull request closed without merging**
