### PR TITLE
NSPanel and NSAlert fixes

### LINKED ISSUE #729: Font preferences not working
When I open the Appearance preferences and try to select a new font it doesn't save the font changes.
I know what the fix is for this.

### PR DESCRIPTION
**Pull request by josh64x2**
Fixes #729 and other build warnings.

### CODE REVIEW

**Comment by josh64x2** [comment]
@barijaona can you please test the changes in 41877cf as I'm not sure if I have done it correctly and I don't know how to test 😄 .

**Comment by barijaona** [comment]
Commit 41877cf does not work for me.

Here are two maneuvers which should display alerts : 
- Download a file with Vienna. Through Finder, remove it from its location in Download folder. Go back to Vienna’s Downloads window. Right click the file and select « Show in Finder » -> You should get an alarm message (Cf. line 138 of DownloadWindow.m)
- Create a Vienna plugin (just duplicate an existing one and add the .viennaplugin file extension). Double-click on it in Finder -> it gets installed in ~/Library/Application Support/Vienna/Plugins and you should get an information message (Cf. line 731 of AppController.m)

**Comment by josh64x2** [comment]
Ooops accidentally deleted :D I will fix up the other commit soon.

**Comment by josh64x2** [comment]
Hey @barijaona I think I've fixed this now. Can you please review? Thanks!!

**Comment by barijaona** [comment]
It’s fine.

**Pull request merged**
