### PR TITLE
Remove XML source window

### PR DESCRIPTION
**Pull request by Eitot**
As briefly discussed in #893. This PR removes the XMLSourceWindow class. Instead, a button is added to the info window where the user can open the cached source file for the feed in the preferred editor for that file type (default is TextEdit).

### CODE REVIEW

**Comment by josh64x2** [comment]
Nice solution! I'll check it out later today and hopefully approve.

**Comment by barijaona** [comment]
It's fine. An item needs to be added in Crowdin for localization of the button text.

**Comment by Eitot** [comment]
I'll import the base translation again on Crowdin. We still need to import the language-specific XLIFF files from Crowdin into the project at release.

**Comment by Eitot** [comment]
I updated the strings at Crowdin. You can now translate the new string there.

**Pull request merged**
