### PR TITLE
Revert "Fix test target"

### PR DESCRIPTION
**Pull request by josh64x2**
Reverts ViennaRSS/vienna-rss#651

This was causing issues with cococapods that were impossible to fix. The time would be better spent on ViennaNG.

### CODE REVIEW

**Comment by josh64x2** [comment]
@barijaona this works ;)

**Comment by josh64x2** [comment]
Also works in the latest betas of Xcode 8 and  macOS 10.12

**Comment by barijaona** [comment]
A reminder : avoid creating test branches in ViennaRSS's remote.

**Comment by josh64x2** [comment]
Yeah GitHub did it automatically when i pressed "Revert" under the PR. I don't know why it would do that.

**Comment by barijaona** [comment]
Ok. I will not attempt to negotiate with Github about what should be the behavior of their web interface ! ;-)

**Pull request merged**
