### PR TITLE
Update pods

### PR DESCRIPTION
**Pull request by Eitot**
FMDB: 2.6 → 2.6.2
OCMock: 3.3 → 3.4
Sparkle: 1.14.0 → 1.16.0

### CODE REVIEW

**Comment by josh64x2** [comment]
Hrm are you using a pre-release version of cocoapods ?

**Comment by Eitot** [comment]
Nope. Just the standard `gem` version.

**Comment by josh64x2** [comment]
haha ok because I just updated my own cocoapods this morning and it was at 1.1.1 😄 
do you want to try and modify `.travis.yml` and put the line `before_script: pod repo update` above the `script` line and see if that fixes the build?

**Comment by josh64x2** [comment]
Oh my bad it should probably be `before_install` instead of `before_script`. Also, does this supersede #774?

**Comment by Eitot** [comment]
#774 should be merged first. ;)

**Comment by Eitot** [comment]
Seems to have worked now.

**Comment by josh64x2** [comment]
Yeah... but now #774 is merged there are conflicts :> you might have to rebase it.

**Pull request merged**
