### PR TITLE
Move MMTabBarView from Carthage to SPM

### PR DESCRIPTION
**Pull request by Eitot**
This PR depends on ViennaRSS/MMTabBarView#30. Once that is merged, the code here as to be updated. I have linked to the `SPM` branch on my fork for testing purposes.

### CODE REVIEW

**Comment by TAKeanice** [comment]
You can proceed with this as I just merged the PR into the MMTabBarView repository.

**Comment by Eitot** [comment]
I am waiting for a tagged release of MMTabBarView (either Vienna’s fork or upsteam).

**Comment by TAKeanice** [comment]
Done that already, see my PR to your branch ;)

**Comment by TAKeanice** [comment]
Feel free to hide the sausage making by only cherry-picking the last commit or squashing my two and your last one into one commit.

**Comment by Eitot** [comment]
Unfortunately, the **v/*** scheme is not supported by SPM. I linked to the commit instead. Maybe if the changes are merged upstream can version tagging be used.

**Comment by TAKeanice** [comment]
SPM supports branch references though, and we can link to the tag by pretending it is a branch.

**Comment by Eitot** [comment]
You are indeed correct! I made the changes.

**Review by barijaona — APPROVED** [review]

**Comment by barijaona** [comment]
Ouups ! I just noticed opening of new tabs is blocked.

**Pull request merged**
