### PR TITLE
Replace ASIHTTPRequest with a wrapper above NSURLSession

### PR DESCRIPTION
**Pull request by barijaona**
The change combines :
- NSURLProtocol to associate pieces of information with NSURLRequest
- NSURLSession and NSOperation (more precisely  [TRVSURLOperation](https://github.com/travisjeffery/TRVSURLSessionOperation)) because Vienna requires some control  over the number of concurrent downloads. Use of operations also makes transitioning our code easier than having to manage blocks and semaphore.

Issue #344

### CODE REVIEW

**Comment by Eitot** [comment]
Very good news! I have been pulling my hair out on this last week. I will have a thorough look at your implementation this weekend.

**Comment by barijaona** [comment]
Duh ! Apparently, I triggered a Github bug !
Commit 3b9ab4a is before cc6799d , but Github displays them in the wrong order…

**Comment by barijaona** [comment]
Note about implementation of OpenReader's methods `-addClientTokenToRequest:` and `-getTokenForRequest:` : I had to use two different approaches for managing dependencies in these methods.

My attempts to use a single approach proved unsuccessful. I guess it is because `addClientTokenToRequest` needs to modify request's HTTP headers, while `getTokenForRequest` needs to modify request's HTTP body.

**Comment by Eitot** [comment]
Performance seems to be similar. I haven’t spotted any problems so far.

We should due extended beta testing for this though, just in case.

**Comment by barijaona** [comment]
You are probably referring to the 'TIC Read Status 1:57' warnings.
I saw them before switching to NSURLSession… and I haven't found any clear explanation about their proliferation since macOS Sierra.
According to this [summary of available info](https://stackoverflow.com/questions/46352735/what-is-tic-read-status-157-in-ios11-xcode-9), they are probably harmless. They could be silenced with an environment variable, but I prefer waiting a little bit before going this way.

**Comment by Eitot** [comment]
Not just those, but also:
```
2018-08-19 14:50:11.958780+0200 Vienna[20763:2558653] Task <A9217E15-6CFC-4D51-ACC4-A586782BD16A>.<1821> HTTP load failed (error code: -1005 [1:57])
2018-08-19 14:50:11.959007+0200 Vienna[20763:2560370] Task <A9217E15-6CFC-4D51-ACC4-A586782BD16A>.<1821> finished with error - code: -1005
2018-08-19 14:50:11.959229+0200 Vienna[20763:2550769] error = Error Domain=NSURLErrorDomain Code=-1005 "The network connection was lost." UserInfo={NSUnderlyingError=0x60c00044ba00 {Error Domain=kCFErrorDomainCFNetwork Code=-1005 “(null)” UserInfo={NSErrorPeerAddressKey=<CFData 0x604001a81bd0 [0x7fff9baa7af0]>{length = 16, capacity = 16, bytes = 0x100201bb17ef1d1f0000000000000000}, _kCFStreamErrorCodeKey=57, _kCFStreamErrorDomainKey=1}}, NSErrorFailingURLStringKey=https://soylentnews.org/index.atom, NSErrorFailingURLKey=https://soylentnews.org/index.atom, _kCFStreamErrorDomainKey=1, _kCFStreamErrorCodeKey=57, NSLocalizedDescription=The network connection was lost.}
```

Also noticed these, but haven’t checked whether these are related:
```
2018-08-19 14:46:09.510875+0200 Vienna[20763:2551150] *** Assertion failure in -[NSXMLDocument insertChild:atIndex:], /BuildRoot/Library/Caches/com.apple.xbs/Sources/Foundation/Foundation-1454.90/Foundation/XML.subproj/XMLTypes.subproj/NSXMLDocument.m:805
```

**Comment by Eitot** [comment]
These status bar appears to be stuck as well, at some point.

Overall though, it seems to work just fine even with over a thousand feeds.

**Comment by barijaona** [comment]
Note that some of the 'TIC Read Status 1:57' warnings are not related to the code modified in this PR.
You can get similar warnings when you open a link in a new (background) tab.

**Pull request merged**
