### PR TITLE
Change TUAW in demo feeds to Six Colors.

### LINKED ISSUE #691: Remove TUAW from Vienna's default subscriptions
It now redirects to some AOL feed of non-Apple related stuff. Probably best to replace with six colours or something?

### PR DESCRIPTION
**Pull request by jesse-c**
Fixes #691.

### CODE REVIEW

**Comment by josh64x2** [comment]
@jesse-c thanks for this! I think we should change out the World of Apple feed too as it seems a bit stale. Any suggestions?

**Comment by barijaona** [comment]
I'd prefer we rebalance the demo feeds with less geeky news sources. Currently, only BBC is not Apple related. In the past, we had a food related feed. Other possible themes : travel, sports…

The idea is to show that a RSS reader can be useful to people who are not addicted to computers :D

**Comment by josh64x2** [comment]
That's a good idea. Any suggestions? It's a shame 500px.com doesn't have any feeds (that I could find anyway).

**Comment by pukku** [comment]
Web comics? XKCD or Foxtrot, for example? How about Postsecret? Maybe a tumblr or two — I'm sure there are some interesting photo tumblrs, and RSS is a handy way to follow them. Atlas Obscura or Amusing Planet are interesting. Astronomy Photo of the Day from NASA?

**Comment by jesse-c** [comment]
So how about:

Apple Hot News: News
BBC: News
[Unsplash](https://unsplash.com/rss): Photography
[Kottke](http://kottke.org/): General interesting/trending things
[Cool Hunting](http://www.coolhunting.com/): Latest in design, technology, style, travel, art and culture
Xkcd: Humour
[A Working Library](aworkinglibrary.com): Literature
[It's Nice That](http://www.itsnicethat.com/): Design
[WIRED](http://www.wired.com/): Technology and many other things

I wanted to find a decent music one but Pitchfork, Slant, etc. don't have RSS feeds. 😐

**Comment by pukku** [comment]
In addition to music, how about a popular podcast? After all, podcasting is basically audio files and RSS... :-) (I would suggest one, but I really only listen to ATP, and the idea is to not be too tech focussed.)

**Comment by josh64x2** [comment]
I like those suggestions except for wired - they have an anti-adblocker thing going on. How about we replace it with arstechnica.com ?

**Comment by jesse-c** [comment]
@pukku I don't really listen to many either. Maybe NPR's Planet Money? It seems to be pretty popular.

@josh64x2 Ars would be a good replacement.

**Comment by josh64x2** [comment]
OK I'm happy with all of those suggestions. How about you @barijaona ? 😄

**Comment by barijaona** [comment]
OK for me. @jesse-c , please push additional commits to your branch before we merge.

**Comment by jesse-c** [comment]
@barijaona @josh64x2 updated!

**Pull request merged**
