### PR TITLE
Update to cocoapods 1.0.1

### PR DESCRIPTION
**Pull request by barijaona**

### CODE REVIEW

**Comment by josh64x2** [comment]
Beat me to it 😄  i'm still waiting for my ruby gems to update!!

**Comment by josh64x2** [comment]
@barijaona are you also getting this error: `ld: library not found for -lASIHTTPRequest` ?

**Comment by barijaona** [comment]
No problem here.

**Comment by josh64x2** [comment]
@barijaona is that with xcode 7.3 or 8?

**Comment by barijaona** [comment]
Xcode 7.3.1

**Comment by josh64x2** [comment]
OK yeah it builds in 7.3.1 but the tests no longer work. I'll try to fix it and if I can't I'll just merge it.

**Comment by josh64x2** [comment]
@barijaona tests are definitely broken after #651 even on OS X 10.11.5 / Xcode 7.3.1. 
Are they working for you at all?

**Comment by barijaona** [comment]
Yes, they work for me in current master.
But this pull request seems to have a problem. I did another `pod update` and got a different result. I will close this and submit another PR.

**Pull request closed without merging**
