### PR TITLE
Database refactor

### PR DESCRIPTION
**Pull request by josh64x2**
Database refactor as per PR #435 but with corrected commit history.
Task list:
- [x] database scheme migration
- [ ] update a few things in the Word document DatabaseSchema.doc (convert to markdown)
- [ ] fix recursive calls to the FMDatabaseQueue
- [ ] create a `@protocol` for future database classes

### CODE REVIEW

**Comment by barijaona** [comment]
There are a lot of changes here : I suggest we publish a Beta before releasing a production version. But we should tackle issue #352 before.

@josh64x2 : do you have other changes in your pipe ?

**Comment by josh64x2** [comment]
I think we should definitely do #380 as well. I wanted to also make some more database changes such as move:
```
-(BOOL)setFolderName:(NSInteger)folderId newName:(NSString *)newName;
-(BOOL)setFolderDescription:(NSInteger)folderId newDescription:(NSString *)newDescription;
-(BOOL)setFolderHomePage:(NSInteger)folderId newHomePage:(NSString *)newLink;
-(BOOL)setFolderFeedURL:(NSInteger)folderId newFeedURL:(NSString *)newFeedURL;
-(BOOL)setFolderUsername:(NSInteger)folderId newUsername:(NSString *)name;
```
into a Folder Database Adaptor. Those functions change Folders, and should not be in the Database class.

**Comment by josh64x2** [comment]
@barijaona I've updated and converted the Database Schema here: https://github.com/ViennaRSS/vienna-rss/wiki/Database-Schema

I can delete the .doc file in my next PR if you are OK with it being in the wiki.

**Comment by barijaona** [comment]
I am OK with it.
A link to the wiki in the "Writing Code" section of the README.md file would be helpful, though.

**Pull request merged**
