### PR TITLE
Workaround for random crashes with some webpages

### PR DESCRIPTION
**Pull request by barijaona**
Issue #1112 and subsequent changes

Replaces #1118

### CODE REVIEW

**Comment by TAKeanice** [comment]
Sorry I was not able to review yet, but will do this weekend.

**Comment by TAKeanice** [comment]
Sorry, it seems like I have been too quick stating that it would solve #1119. It did for the first time, but now it is back to its old state (second or third time opening Vienna). Are the preferences you are using for disabling plugins and javascript on close persistent across launches?

**Comment by barijaona** [comment]
No, the preferences changes aren't persistent.

**Comment by TAKeanice** [comment]
See my new issue on that. Apparently, dealloc and thus also `handleStopLoading` on browserPane is only called when the tab is closed via the close button, not via cmd+w.

**Pull request merged**
