### PR TITLE
New Crowdin translations

### PR DESCRIPTION
**Pull request by Eitot**
Enjoy!

### CODE REVIEW

**Comment by Eitot** [comment]
It seems that Crowdin more or less recognises the renamed file names. I am currently sanitising the “translation memory” a bit.

**Comment by barijaona** [comment]
This is what I did after problems caused by #1087 :  
- I backed up locally all Crowdin translations,
- uploaded the updated en.xliff
- fixed the references to original files in the localized .xliff
- reimported them into Crowdin

Seemed to work, but requires patience as Crowdin needs time to send pull requests to Github.

**Comment by Eitot** [comment]
Maybe we should create an export script as well. There is no reason to translate the Info.plist files, but Xcode insists on exporting/importing them. :/

**Comment by barijaona** [comment]
The project fails to build if you don't have the InfoPlist.strings files 😞 
Don't fight with Xcode 🤕

**Comment by Eitot** [comment]
I don’t know why the Ruby script failes when executed from Xcode. In the command line it seems to work just fine :/

**Comment by Eitot** [comment]
@barijaona Can you try building it? I’ve removed the Infoplist.strings files again and had no issues. They are recreated upon importing, but it should be easy enough to just ditch them again.

**Comment by Eitot** [comment]
Only get this warning now. I’ve concluded that Xcode will create UTF16-encoded files now when importing XLIFF files.

> Vienna/Resources/da.lproj/Localizable.strings:0: warning: validation failed: The data couldn’t be read because it isn’t in the correct format.
> Vienna/Resources/da.lproj/Localizable.strings:0: warning: the specified input encoding is Unicode (UTF-8), but file contents appear to be Unicode (UTF-16); treating as Unicode (UTF-16).

**Comment by barijaona** [comment]
Your current version builds.
But as soon as I run the ruby script, references to the Info.plist files are added into Vienna.xcodeproj/project.pbxproj and I got errors :  
````
CopyStringsFile /Users/barijaon/Library/Developer/Xcode/DerivedData/Vienna-efbpewbluhvhohgcxzmpuvimcyhg/Build/Products/Development/Vienna.app/Contents/Resources/da.lproj/InfoPlist.strings Vienna/da.lproj/InfoPlist.strings
    cd /Users/barijaon/gitdirs/vienna-rss
    builtin-copyStrings --validate --inputencoding utf-8 --outputencoding UTF-16 --outdir /Users/barijaon/Library/Developer/Xcode/DerivedData/Vienna-efbpewbluhvhohgcxzmpuvimcyhg/Build/Products/Development/Vienna.app/Contents/Resources/da.lproj -- Vienna/da.lproj/InfoPlist.strings

error: failed to remove /Users/barijaon/Library/Developer/Xcode/DerivedData/Vienna-efbpewbluhvhohgcxzmpuvimcyhg/Build/Products/Development/Vienna.app/Contents/Resources/da.lproj/InfoPlist.strings: “InfoPlist.strings” couldn’t be removed.
```

**Comment by Eitot** [comment]
All right, I suppose we could move the Info.plist file to the Vienna/Resources directory as well. Then we just accept the strings files.

**Comment by Eitot** [comment]
I think I found a solution. Xcode seems to recognise when a file called InfoPlist.strings is already present somewhere. It won’t export a new InfoPlist.strings in the XLIFF, but take the one that is there. So we can keep the Info.plist in `Vienna/` as long as there is `Vienna/Resources/Base.lproj/InfoPlist.strings`.

**Comment by Eitot** [comment]
I think the problem with the encoding is because of this:
screen shot 2018-05-06 at 12 03 53
screen shot 2018-05-06 at 12 04 09

**Comment by barijaona** [comment]
Definitely linking to Localizable.strings, but multiple files seem involved here…

**Comment by barijaona** [comment]
Useful command : 
````
plutil -lint Vienna/Resources/de.lproj/Localizable.strings
````

We need something to handle embedded quotation marks…

**Comment by barijaona** [comment]
These two regexes are a quick workaround for embedded quotation marks : 
Replace
````regex
(= ".*[^\\])\"(.*)\"(.*\";)
````
with
````regex
\1\\"\2\\"\3
````

then replace
````regex
= \"\"(.*)\"(.*\";)
````
with
````regex
= "\\"\1\\"\2
````

**Pull request merged**
