### PR TITLE
Improve speed with large databases

### PR DESCRIPTION
**Pull request by barijaona**
Add indexes for selecting read/unread messages and deleted/non deleted
messages.

Credits to user karstenwo on cocoaforge.com
https://forums.cocoaforge.com/viewtopic.php?f=18&t=27244

### CODE REVIEW

**Review by Eitot — COMMENTED** [review]
Is it not necessary to reindex the database?

**Comment by barijaona** [comment]
It is not necessary.

Reindexing might be useful when the definition of a collation sequence has changed. This is not the case.
Reindexing might also be useful to fix any index corruption. But if you have index corruption, that is a symptom
of deeper problems which should be addressed.

While we are at it, I am now asking myself if the change made in version 22 of the database is the right one. [The call to `compactDatabase` was suppressed](https://github.com/ViennaRSS/vienna-rss/commit/93dd835fe1419b46cec2a246be700c4201bd16ca#diff-7a738118de55fdd3871ed41c0af2dd127577789d867bab2e8aa177a2eb37194bL1691), but having `auto_vacuum=1` and calling VACUUM are [not equivalent](https://www.sqlite.org/lang_vacuum.html):

>  When auto_vacuum is enabled for a database free pages may be reclaimed after deleting data, causing the file to shrink, without rebuilding the entire database using VACUUM. However, using auto_vacuum can lead to extra database file fragmentation. And auto_vacuum does not compact partially filled pages of the database as VACUUM does.

**Comment by Eitot** [comment]
See: https://github.com/ViennaRSS/vienna-rss/issues/529#issuecomment-751459607 for the reasoning behind `auto_vacuum`. 

It might still be necessary to run `VACUUM` every now and then, but absolutely not every time when Vienna closes and stops it from closing for potentially minutes.

**Review by Eitot — APPROVED** [review]

**Comment by barijaona** [comment]
It might be interesting (through another pull request) to replace in the Vienna menu "Reindex the Database" with "Reindex and Optimize the Database" which would combine REINDEX and VACUUM.

It is also [suggested](https://www.sqlite.org/lang_analyze.html) to run `PRAGMA optimize` before closing the database.

**Review by Eitot — APPROVED** [review]

**Pull request merged**
