### PR TITLE
Add a "Delete" icon to menu bar

### PR DESCRIPTION
**Pull request by TAKeanice**
Adds menu bar icon for article deletion. @3x image missing, see discussion in #1069

### CODE REVIEW

**Review by josh64x2 — APPROVED** [review]

**Comment by TAKeanice** [comment]
Sorry @josh64x2 , I had trouble with case sensitivity and thus needed to force-push, plus I overlooked the validation part.

**Comment by barijaona** [comment]
The tool tip is wrong. It's currently "Email a link to the current article or website" 😄

**Review by barijaona — CHANGES_REQUESTED** [review]
Please fix the tool tip. It's currently "Email a link to the current article or website".
Suggestion : "Delete the current article"

**Comment by TAKeanice** [comment]
> Please fix the tool tip. It's currently "Email a link to the current article or website".
> Suggestion : "Delete the current article"

Done that and replaced the image with the just uploaded universal vector graphic. I chose the version without arrow, if decided otherwise, I can change it to the version with arrow.

**Review by barijaona — APPROVED** [review]

**Pull request merged**
