### PR TITLE
Add printing support to the new browser

### PR DESCRIPTION
**Pull request by Eitot**
This uses private WebKit APIs on systems before macOS 11.

I have not tested this on any older systems (I have no access to those anymore, since I am using an M1 Mac). Can someone test this on macOS 10.12 or macOS 10.13?

### CODE REVIEW

**Review by TAKeanice — APPROVED** [review]
I have tested on Ventura and there, it looks great. However, for my taste, the margins on the page are a little too narrow. Possibly something we could let the users set in the future?

**Comment by TAKeanice** [comment]
I will try to set up MacOs 10.12 (Sierra) on Virtualbox (https://en.wikibooks.org/wiki/VirtualBox/Setting_up_a_Virtual_Machine/Mac_OS_X) and test Vienna there tomorrow

**Comment by TAKeanice** [comment]
I think we should not overdo it; basic printing support should be enough. The margins are a matter of taste, I think we should either take the easy route first and allow the user to set them somewhere in Vienna, or just hint him at the alternative of adding the site in Safari and printing from there.

**Comment by barijaona** [comment]
I haven't yet setup a 10.13 virtual machine, but I have backported the pull request to 10.12 and it works as expected.

But I see a lot of `TODO`'s present in the remaining code.
So, I think it's time to fix what appears to me to be an historical inconsistency:
- we currently require a `printPage` function in the `Tab` protocol.
- requiring a `printDocument` function would be more straightforward

**Comment by barijaona** [comment]
I wasn't precise enough, my intent was `printDocument(_ sender: Any?)`

**Review by barijaona — APPROVED** [review]

**Pull request merged**
