### PR TITLE
Add dark mode support to some Vienna styles

### PR DESCRIPTION
**Pull request by barijaona**
- Change CSS of default style (Tyger graphite) to include a dark scheme
- Merge Serifim Dark and Serifim Light into a single version

### CODE REVIEW

**Comment by barijaona** [comment]
I tried to reflect the originals as faithfully as possible; graphic designer's opinions desired.

**Comment by Eitot** [comment]
Are CSS variables supported as early as El Capitan?

**Comment by barijaona** [comment]
This might be seen as a regression for someone using Serifim Dark with a pre-10.14 version of macOS. But it is still possible to custom install older version of Serifim Dark if one prefers the "always dark" version.

**Comment by Eitot** [comment]
The Tyger dark style is a bit too contrast heavy. I think the text colour can should be less bright and the link colour should have more muted colour. Compare Safari’s reader mode: `#b0b0b0` for text and `#5ac8fa` for links.

**Comment by barijaona** [comment]
I confirm that CSS custom properties are supported by the latest standard El Capitan installation (10.11.6)

**Review by Eitot — APPROVED** [review]

**Comment by Eitot** [comment]
Side note: The FeedLight styles have small text on a HIDPI display. I never noticed until now, because I used a minimum font size.

**Pull request merged**
