### PR TITLE
Set deployment target to OS X 10.8

### PR DESCRIPTION
**Pull request by josh64x2**
Updated the target in the Podfile and in the xcode project.
See: https://github.com/ViennaRSS/vienna-rss/pull/474#issuecomment-126738166

### CODE REVIEW

**Comment by dak180** [comment]
See josh64x2/vienna-rss#14

**Comment by barijaona** [comment]
Did not work here. See https://github.com/josh64x2/vienna-rss/pull/15

**Comment by barijaona** [comment]
For info, I use version 0.36.0.beta.2 of cocoapods.

**Comment by josh64x2** [comment]
@barijaona 0.38.2 is the latest stable version. are you able to update and try again?

**Comment by barijaona** [comment]
I updated cocoapods, but the build still fails, complaining about missing files, like : 
Pods/Target Support Files/ASIHTTPRequest/ASIHTTPRequest-Private.xcconfig
Pods/Target Support Files/MASPreferences/MASPreferences-Private.xcconfig

Did you run `pod update` in your environment ?

**Comment by barijaona** [comment]
I can't understand why the 0.38.2 version of cocoapods keeps the Pods/JSONKit folder…

**Comment by josh64x2** [comment]
Yeah that is odd!

**Pull request merged**
