### PR TITLE
Raise deployment target to OS X 10.11 El Capitan

### PR DESCRIPTION
**Pull request by Eitot**
Relevant discussion: #1217

### CODE REVIEW

**Comment by Eitot** [comment]
Any thoughts on going further than this (with <s>10.16</s> 11.0 on the horizon)?

**Comment by josh64x2** [comment]
> Any thoughts on going further than this (with 10.16 11.0 on the horizon)?

Based on https://github.com/ViennaRSS/vienna-rss/projects/5 we already have a lot to gain by moving to 10.11, so perhaps we should start there, and then look at the 10.12 stuff after?

**Comment by josh64x2** [comment]
This has been dragging on for years, so I'm give it 72 hours for comment and then merge it by the weekend.

**Comment by josh64x2** [comment]
@Eitot if you can please update the README.md file to reflect the new minimum supported versions and remove the draft label, then I will approve it.

**Comment by josh64x2** [comment]
Merging based on https://github.com/ViennaRSS/vienna-rss/issues/1217#issuecomment-450607954

**Pull request merged**
