### PR TITLE
Replace NSURLDownload with NSURLSessionDownloadTask

### PR DESCRIPTION
**Pull request by Eitot**
NSURLDownload methods are deprecated. This resolves the build warning in Xcode.

There is some (IMO minor) loss of functionality here, particularly:
- `-(BOOL)download:(NSURLDownload *)download shouldDecodeSourceDataOfMIMEType:(NSString *)encodingType`
- `-(void)download:(NSURLDownload *)download decideDestinationWithSuggestedFilename:(NSString *)filename`

To do:
- [x] Find a workaround for legacy WebView’s `downloadDelegate`
- [ ] Link WebKit (WKWebView) to this or adopt WKDownload (macOS 11.3+)
- [ ] ~~Handle duplicate file names (#1472)~~
- [x] Use NSFileManager to retrieve the downloads path
---
I also changed the way in which the download folder is handled. Rather than storing a string in NSUserDefaults, it now uses a security-scoped URL that is stored as NSData in NSUserDefaults, which is required for sandboxing. This may not work reliably in development builds due to code-signing requirements (the security-scoped bookmarks require an entitlement).

### CODE REVIEW

**Comment by Eitot** [comment]
I kept the old WebDownloadDelegate code for the WebKitLegacy browser. The only thing that does not work is downloads from the WebKit browser (context menus and such).

**Comment by barijaona** [comment]
Using the old browser, just clicking on a link without using the download contextual menu item, I get an exception:

````
2021-10-05 16:24:10.616421+0300 Vienna[12965:949317] [General] *** -[NSFileManager moveItemAtPath:toPath:error:]: destination path is nil
2021-10-05 16:24:10.616895+0300 Vienna[12965:950709] ScanAllPluginsInLibrary: load Library [/System/Library/Filesystems/NetFSPlugins]
2021-10-05 16:24:10.617440+0300 Vienna[12965:949317] [General] (
	0   CoreFoundation                      0x00007fff2048a1db __exceptionPreprocess + 242
	1   libobjc.A.dylib                     0x00007fff201c3d92 objc_exception_throw + 48
	2   Foundation                          0x00007fff211ec997 +[NSFilesystemItemMoveOperation filesystemItemMoveOperationWithSourceURL:destinationURL:options:] + 0
	3   Vienna                              0x000000010f3c060a -[DownloadManager download:didCreateDestination:] + 218
	4   JavaScriptCore                      0x00007fff373995dd _ZN3WTF7RunLoop11performWorkEv + 573
	5   JavaScriptCore                      0x00007fff3739a34a _ZN3WTF7RunLoop11performWorkEPv + 26
````

**Comment by Eitot** [comment]
Just clicking on a link? Hmm I did admittedly not test that. I will check it out. The context menu I did test.

**Comment by Eitot** [comment]
@barijaona This is actually a latent bug that is probably present for some time. It occurs in the releases too. It might have been introduced when the `‑download:didCreateDestination:` callback was added in 9aa332f5f98fdd85b8d02fae190b69e3de765353. For some reason, `‑downloadDidBegin:` is not called (at all), which is responsible for creating the download item. This only seems to occur in this specific instance.

**Comment by Eitot** [comment]
I have submitted a band-aid fix.

The problem is that downloads started by clicking on a file URL in WebKitLegacy are partially bypassing the WebDownloadDelegate. TabbedWebView’s `‑webView:decidePolicyForMIMEType:request:frame:decisionListener:` delegate callback ends up calling the `download` method. [The documentation](https://developer.apple.com/documentation/webkit/webpolicydecisionlistener/1537456-download?language=objc) implies that at this point the download has already started and is simply passed to the WebDownloadDelegate for its completion. It is not known which handlers are still called at that point, but I added workaround to the two most obvious ones.

**Pull request merged**
