### PR TITLE
Turn BrowserView tabView variable into property

### PR DESCRIPTION
**Pull request by Eitot**
The instance variable clashed with a local variable in a delegate method.

### CODE REVIEW

**Comment by josh64x2** [comment]
@barijaona as per @Eitot's comment, there was a naming conflict and it resulted in an Xcode warning.
Side note: we should think of a convention for when to use `self.instanceVariable` and `_instanceVariable`.

**Comment by Eitot** [comment]
Is there a need for custom ivars at all? I basically learned to just use properties and let the compiler handle the synthesising and ivar naming (in the setters/getters). I find it odd now to declare private ivars in the header file. 🤔

**Comment by josh64x2** [comment]
Oh it's not for custom ivars - Xcode auto-synthesizes your `@property` to `_ivar`, and you can access it using either `self.ivar` or `_ivar`. I think they are basically synonymous so it is more of a code convention thing.

I guess with the move to Swift being inevitable, `self.ivar` makes more sense.

**Comment by Eitot** [comment]
I learned to use _ivar only within the setters/getters to which they belong. Outside of those, you use self.property. You will see the _ivars only if you actually write the setters/getters.

**Comment by josh64x2** [comment]
@Eitot if possible can you please also create pull requests against the new `legacy3.1.x` branch for this change, the sparkle one, and the help bundle one, and potentially the preferences window controller change... thanks 😄

**Comment by Eitot** [comment]
Can I just merge them into one pull request? I already deleted my branches. :/

**Comment by josh64x2** [comment]
Haha and I deleted my local copies of your branches. I'll try to cherry pick them into new branches tomorrow.

I think if changes can easily be merged into the legacy branch then we should merge them. It would be a waste of time fixing anything but a trivial merge conflict however.

**Comment by josh64x2** [comment]
Oh sometimes you can 'undelete' a branch from GitHub, check #805 down the bottom where it says you deleted your branch and sometimes there is a restore button you can use.

**Comment by Eitot** [comment]
What do you mean with ‘the help book one’?

**Comment by barijaona** [comment]
Reminder : our CONTRIBUTING.md file advises to follow [Spotify's style](https://github.com/spotify/ios-style) which says : 

> Set and access properties using dot notation:
`self.myString = @"A string";`
Except in the `init` or `dealloc` methods, always use the ivar directly there:
`_myString = nil;`

**Comment by josh64x2** [comment]
@barijaona yup you're right - I knew it was probably in there but I was too tired to check 😅

**Pull request merged**
