### PR TITLE
More UI changes for Big Sur

### PR DESCRIPTION
**Pull request by Eitot**
Updates the tab icons in the preferences window. I used the @ icon for the syncing to have consistency with Apple’s apps, notably Mail. The icon for the updates tab looks similar to the icon for the syncing tab, however. If anyone sees better SF Symbols for these tabs, please suggest them.

It also removes the unnecessary script icon for the menu bar (there appears to be a system-provided image for this).

Screenshot 2020-11-15 at 10 02 02

### CODE REVIEW

**Comment by barijaona** [comment]
The @ icon is universally associated to e-mail, so I think we should not use it here.

For 'Sync', I would rather use the symbol you initially chose for 'Updates' (`arrow.triangle.2.circlepath`) or (better in my opinion) the one named `rectangle.and.arrow.up.right.and.arrow.down.left` 

For 'Updates', I would go with `arrow.down.app`

**Comment by barijaona** [comment]
For 'General', a possible alternative would be `dial.min`

For 'Advanced', a good alternative would be `wrench.and.screwdriver`

**Comment by barijaona** [comment]
For 'General', `switch.2` is similar to what we already have.

To sum it up, my preference goes to : 
- `switch.2` for General
- `paintbrush` for Appearance (as you suggested)
- `rectangle.and.arrow.up.right.and.arrow.down.left` for Syncing
- `arrow.down.app` for Updates
- `wrench.and.screwdriver`for Advanced

**Comment by Eitot** [comment]
> For 'Sync', I would rather use the symbol you initially chose for 'Updates' (arrow.triangle.2.circlepath) or (better in my opinion) the one named rectangle.and.arrow.up.right.and.arrow.down.left

Screenshot 2020-11-15 at 16 24 43

The latter symbol does not look that strong to me. I am not sure what it is supposed to symbolise.

> For 'Updates', I would go with arrow.down.app
Screenshot 2020-11-15 at 16 23 50Screenshot 2020-11-15 at 16 31 16

That one looks like a good alternative. The second one may be a variant (App Store uses the same one for the updates tab).

> For 'General', a possible alternative would be `dial.min`
Screenshot 2020-11-15 at 16 22 35

The icon for general preferences is so commonly used across Apple’s apps that I would rather not change it.

> For 'Advanced', a good alternative would be `wrench.and.screwdriver`
Screenshot 2020-11-15 at 16 20 53

This one looks good. I agree on this one. However, the two cogs icon is frequently used in Apple’s apps (Finder, Safari, Music, Podcasts, among others).

**Comment by Eitot** [comment]
Screenshot 2020-11-15 at 16 39 03
Screenshot 2020-11-15 at 16 39 30

**Comment by barijaona** [comment]
I am OK with this one.

> Screenshot 2020-11-15 at 16 39 03
>

**Comment by Eitot** [comment]
I also added some configurations to support system-generated document icons (Vienna plug-ins and styles). This is new to Big Sur as well. I have not found any documentation other than this [Apple developer article](https://developer.apple.com/news/?id=5i6jlf4d).

I have not seen the result yet, so I am not sure if this works. This probably has to be tested with a beta version.

**Comment by Eitot** [comment]
It should work now.

Screenshot 2020-11-16 at 02 25 47
Screenshot 2020-11-16 at 02 26 11

Perhaps the “Vienna” label should be dropped from the icon?

**Comment by barijaona** [comment]
Let's keep the Vienna label in the icons for the time being.

**Review by barijaona — APPROVED** [review]

**Comment by barijaona** [comment]
Besides, I am wondering why the following settings aren't located in the 'Appearance' tab :
- show in menu bar
- show the unread count on the application icon

**Comment by Eitot** [comment]
> Besides, I am wondering why the following settings aren't located in the 'Appearance' tab :
> 
> * show in menu bar
> * show the unread count on the application icon

It has been like that for many years. I would say that the current settings in the appearance tab are only aesthetic. The menu item and the unread count have a functional purpose.

**Comment by barijaona** [comment]
Yes, this has been the situation for many years now. But wouldn't it be the best time to change that? The benefit would be to unclutter the General tab.

**Comment by Eitot** [comment]
I don’t mind moving those settings to the appearance tab. But it was out of scope for this PR anyway.

**Comment by barijaona** [comment]
I just mentioned this idea as an aside point slightly related to this PR, because your recent efforts are towards revamping the Preferences.

**Comment by Eitot** [comment]
I'll have a look.

**Pull request merged**
