### PR TITLE
Fix unwanted refresh of article at end of sync

### PR DESCRIPTION
**Pull request by barijaona**
Issue #934

### CODE REVIEW

**Comment by lapcat** [comment]
What happens when guid is non-nil but the article is not found? Then the old row is still selected, but it's not the old article.

**Comment by barijaona** [comment]
Amended following @lapcat 's comment

**Comment by lapcat** [comment]
Wouldn't that make currentSelectedRow get out of sync?

**Comment by barijaona** [comment]
`currentSelectedRow` is synchronized by the `-tableViewSelectionDidChange:` delegate.

I note that there are a few direct manipulations of `currentSelectedRow` in existing code, but many of them seem superfluous because the delegate will eventually be called.

**Pull request merged**
