### PR TITLE
Toolbar Icons from #791

### PR DESCRIPTION
**Pull request by Aoiike**
Added PDF Icons to a new directory.

### CODE REVIEW

**Comment by Eitot** [comment]
If you want, you can add yourself to the Credits.rtf file in the root directory.

**Comment by Eitot** [comment]
Unfortunately, it does not appear to be possible to use separate PDF files for the different scaling factors of the same image. I think these images here need raster versions:
- ViGetInfo@2x.pdf
- ViNewFeed@2x.pdf
- ViSync@2x.pdf

This is how it would look:
screen shot 2017-07-01 at 12 02 53

**Comment by Aoiike** [comment]
I think I got it working before with vectors, I'll boot into my dev drive and check.

**Comment by Aoiike** [comment]
I found it, I had to manually set them to Template Image in the Render As dropdown in the top right, then they scaled automatically.
screen shot 2017-07-01 at 12 10 41
This is with XCode 8.2.1, I think it's the same in the current version.

**Comment by Eitot** [comment]
You are correct, it now works. You can check out my [`window-controller`](https://github.com/Eitot/vienna-rss/tree/window-controller) branch.

**Comment by JanX2** [comment]
May I suggest postfixing the file names with “Template”? This turns them into Template Images automatically and also signals everywhere, that they are.

**Comment by Eitot** [comment]
I have already named the image assets "*Template". Does it have to extend to the actual file names too?

**Comment by barijaona** [comment]
I might be too conservative, but I don't find the look of the ViSync icon very intuitive.

**Comment by barijaona** [comment]
Same remark for the ViEmptyTash icon.

**Comment by JanX2** [comment]
@Eitot I believe so.

**Comment by Aoiike** [comment]
@barijaona the ViEmptyTrash Icon should be easier to identify when paired with the sidebar's Trash Icon which uses the same shape.
trash 2x emptytrash 2x


The ViSync Icon is an interesting one, it's probably taken me the longest of all the Icons to get to the state it's in now, and it was also the template for the style of the rest of the Icons.
I think it makes enough sense to be able to associate easily after using it or reading the tooltip,
there's also the version in the Preferences Toolbar, which looks like this so far.
screen shot 2017-07-09 at 23 28 10 80

**Comment by barijaona** [comment]
I’d suggest testing an upside down look for the trash icon.

The color version of the sync icon is significantly more legible than the black and white one. Did you consider a greyscale version?

**Comment by josh64x2** [comment]
Would greyscale be appropriate for this? I don't recall seeing greyscale in any mac apps using template style toolbar icons.

**Comment by josh64x2** [comment]
For what it is worth, I'm happy with the new sync icon, but I'm wondering @barijaona if you have a sketch or something so I can understand what you'd like to see?

**Comment by JanX2** [comment]
@josh64x2 When using grayscale in a Template, this is usually interpreted as Z-depth and shaded accordingly.

**Comment by barijaona** [comment]
@josh64x2 I am not all a designer but I think the role of the sync icon would be easier to understand if its shape evoked more directly a loop.

I understand that @Aoiike wanted to break from the current circular shape, but maybe having more identifiable arrows would be possible ?

**Comment by josh64x2** [comment]
@barijaona yup that could work :)

**Comment by Aoiike** [comment]
I haven't seen any Toolbar Icons using Alpha Gradation, only flat segments of different Alpha. That said, the Updated macOS UI Guidelines don't mention anything about it either way, and I think it looks good with the Gradient.
visync


what I'm not sure about is if it renders correctly with XCode. I'm also thinking about dropping the @2x version and using the same weight for all sizes.

**Comment by Eitot** [comment]
I think the icon just isn't very recognisable. The spinning arrows by themselves are already fairly abstract and this custom shape does not reinforce the them.

Maybe we should reconsider the icon altogether. At the end of the day, this button is meant to convey: fetch new content. Maybe something simple such as feed icon with an arrow on the side would be more obvious. Even Apple Mail sticks with an envelope icon.

**Comment by Aoiike** [comment]
What about a "Vienna" Icon, that also happens to resemble an RSS Icon with a Down Arrow?
rss-icons
(ViNewFeed is there to show the distinction)

I like the Idea of following Mail as the function is very similar to Get Mail, might also be more appropriate to call it ViUpdate rather than ViSync.

**Comment by josh64x2** [comment]
@Aoiike I like it!

**Comment by Eitot** [comment]
Definitely looks appealing! I prefer that one. Can you also make icons for the share button (the system one has thinner lines, which might not fit your style) and style button? You could take inspiration from these:
screen shot 2017-07-12 at 14 19 24screen shot 2017-07-12 at 14 19 35screen shot 2017-07-12 at 14 20 03

I think we might also want to add a toggle to load the full HTML page of the feed item as opposed to just the snippet. This can currently be enabled in the Get Info window on a per-feed basis, but it might be nice to have something in the toolbar for this to toggle ad-hoc.

I was thinking whether we should change the "add feed" toolbar item into something like Photos has:
screen shot 2017-07-12 at 14 29 04


However, this icon style is more reminiscent of the sidebar, rather than toolbar icons.

**Comment by Aoiike** [comment]
I wouldn't want to alter the Share Button Icon without a functional need to, it's designed to be ubiquitous across all Apple platforms so it feels like it would be making a change for the sake of change. (and Mavericks still uses the old one)

I already have a Style Icon, which I've been meaning to update in #871 
style menu
The design is meant to be very similar to the many Browser Extensions that override site CSS, because the function is almost identical.

For the Add Feed button, I think keep the look it has now with a Click to Add feed, and add a Click+Hold/Force Click to bring up the "Add _" menu, the same way the Reading List button in Safari's Address Bar works.
The way Photos uses the Sidebar style Rendering makes sense because whichever option you pick adds an item to the Sidebar with the same Icon, I think that would work here too.

**Comment by Eitot** [comment]
> I wouldn't want to alter the Share Button Icon without a functional need to, it's designed to be ubiquitous across all Apple platforms so it feels like it would be making a change for the sake of change. (and Mavericks still uses the old one)

I prefer having a consistent look (which is also a recommendation in Apple‘s HIG). You have adopted your own style with thicker lines and custom shapes. I think we should commit to this completely. Besides, we are not using the share sheet just yet and by the time we might, Mavericks may not even be supported anymore.

> I already have a Style Icon, which I've been meaning to update in #871
style menu
>The design is meant to be very similar to the many Browser Extensions that override site CSS, because the function is almost identical.

I am not sure I like this rather technical icon. Also mind you: `<s>` often means <s>strike-though</s>. Perhaps something more intuitive?

>For the Add Feed button, I think keep the look it has now with a Click to Add feed, and add a Click+Hold/Force Click to bring up the "Add _" menu, the same way the Reading List button in Safari's Address Bar works.
>The way Photos uses the Sidebar style Rendering makes sense because whichever option you pick adds an item to the Sidebar with the same Icon, I think that would work here too.

Hiding functionality behind modifier keys always comes at a cost. Despite what Apple may consider acceptable, I commit to only doing this when the function is rarely used and the UI does not allow for a reasonable alternative. A popup button is that alternative and adding a folder from the toolbar isn't an advanced feature. Combining modifier keys with toolbar icons is very rare even in Apple apps.

**Comment by Aoiike** [comment]
For the Style Icon, I haven't seen a really intuitive Icon for this kind of feature anywhere else, and with the current one looking like a Window Layout menu or Sidebar Toggle, anything unique would be an improvement.
The ‹S› itself is made up from the most frequently recurring features in Icons of CSS Extensions for Chrome, Safari, and Firefox, which were a formatted S, </>, or just "CSS" in some kind of shape. The Strikethrough thing only happens in code, it's generally a letter with a line through for Icons.

This is how everything looks together so far.
compositionv3

**Comment by barijaona** [comment]
The greyscale icon does not render correctly in Xcode. Sorry about that.
So I prefer the "down arrow" look for the ViSync (or ViUpdate) icon.

**Comment by barijaona** [comment]
I'll close this as the new icons are already included in master branch.

**Pull request closed without merging**
